### ISSUE TITLE
Parseo de kudo cuando hay mas de un "por"

### ISSUE THREAD

**Issue by agusgs** [10Pines/kudo-wall#11]
Cuando pones mas de un por en el kudo toma el ultimo por como separador del para quien fue.
Ejemplo:

- En slack pongo:
    + kudo para joaco por ser tan capo de crear el kudo wall y por solucionar este issue :smile: 
- El kudo lo muestra en la pagina web como:
    + titulo: kudo para joaco por ser tan capo de crear el kudo wall y
    + cuerpo: por solucionar este issue :smile:

![image](https://cloud.githubusercontent.com/assets/12557810/18213112/f13d34f4-711c-11e6-9455-f799caed3b6c.png)

**Comment by jazcarate** [comment]
#12 arregla esto 💃
